### ISSUE TITLE
Unable to create yii basic application. Fails on mkdir()

### ISSUE THREAD

**Issue by pjjk** [pjjk/yii#1]
Hi
Newbie with this, so I am not getting far. I am trying to set up the basic Yii application but it fails on mkdir()
The BaseFileHelper documentation says 'do not use' but I cannot see where it is being referenced from.

Any ideas?

Stack trace is below (edited myroot)

Exception (Exception) 'yii\base\Exception' with message 'Failed to create directory "myroot\basic\runtime/logs": mkdir(): Permission denied' 

in myroot\basic\vendor\yiisoft\yii2\helpers\BaseFileHelper.php:482

Stack trace:
#0 myroot\basic\vendor\yiisoft\yii2\log\FileTarget.php(90): yii\helpers\BaseFileHelper::createDirectory(myroot\\...', 509, true)
#1 myroot\basic\vendor\yiisoft\yii2\base\Object.php(107): yii\log\FileTarget->init()
#2 [internal function]: yii\base\Object->__construct(Array)
#3 myroot\basic\vendor\yiisoft\yii2\di\Container.php(374): ReflectionClass->newInstanceArgs(Array)
#4 myroot\basic\vendor\yiisoft\yii2\di\Container.php(153): yii\di\Container->build('yii\\log\\FileTar...', Array, Array)
#5 myroot\basic\vendor\yiisoft\yii2\BaseYii.php(344): yii\di\Container->get('yii\\log\\FileTar...', Array, Array)
#6 myroot\basic\vendor\yiisoft\yii2\log\Dispatcher.php(101): yii\BaseYii::createObject(Array)
#7 myroot\basic\vendor\yiisoft\yii2\base\Object.php(107): yii\log\Dispatcher->init()
#8 myroot\basic\vendor\yiisoft\yii2\log\Dispatcher.php(89): yii\base\Object->__construct(Array)
#9 [internal function]: yii\log\Dispatcher->__construct(Array)
#10 myroot\basic\vendor\yiisoft\yii2\di\Container.php(374): ReflectionClass->newInstanceArgs(Array)
#11 myroot\basic\vendor\yiisoft\yii2\di\Container.php(153): yii\di\Container->build('yii\\log\\Dispatc...', Array, Array)
#12 myroot\basic\vendor\yiisoft\yii2\BaseYii.php(344): yii\di\Container->get('yii\\log\\Dispatc...', Array, Array)
#13 myroot\basic\vendor\yiisoft\yii2\di\ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#14 myroot\basic\vendor\yiisoft\yii2\base\Application.php(302): yii\di\ServiceLocator->get('log')
#15 myroot\basic\vendor\yiisoft\yii2\web\Application.php(63): yii\base\Application->bootstrap()
#16 myroot\basic\vendor\yiisoft\yii2\base\Application.php(267): yii\web\Application->bootstrap()
#17 myroot\basic\vendor\yiisoft\yii2\base\Object.php(107): yii\base\Application->init()
#18 myroot\basic\vendor\yiisoft\yii2\base\Application.php(206): yii\base\Object->__construct(Array)
#19 myroot\basic\web\index.php(15): yii\base\Application->__construct(Array)
#20 {main}

**Comment by pjjk** [comment]
Changed directory permissions and all sorted now. Ima nube :(
